# @package _global_
defaults:
  - /task/g1_cricket_approach_feedback/mjbatch
  - _self_

env:
  auto_reset: false
  actions:
    residual:
      _target_: unilab.tasks.manipulation.g1_cricket.moving_delivery.MovingDeliveryActionCfg
      reference_directory: g1_cricket_results/running_fore_aft_support_v1
  observations:
    policy:
      terms:
        command:
          func: unilab.tasks.manipulation.g1_cricket.moving_delivery.moving_command
